### ISSUE TITLE
class org.apache.fury.serializer.ObjectSerializer cannot be cast to class org.apache.fury.serializer.collection.AbstractCollectionSerializer

### ISSUE THREAD

**Issue by KouShenhai** [apache/fury#1724]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

0.5.1

### Component(s)

Java

### Minimal reproduce step

[FuryFactory.java](https://github.com/KouShenhai/KCloud-Platform-IoT/blob/master/laokou-common/laokou-common-mybatis-plus/src/main/java/org/laokou/common/mybatisplus/config/FuryFactory.java)

[FurySerialCaffeineJsqlParseCache.java](https://github.com/KouShenhai/KCloud-Platform-IoT/blob/master/laokou-common/laokou-common-mybatis-plus/src/main/java/org/laokou/common/mybatisplus/config/FurySerialCaffeineJsqlParseCache.java)

```java
	static {
		JsqlParserGlobal.setJsqlParseCache(new FurySerialCaffeineJsqlParseCache(
				cache -> cache.maximumSize(1024).expireAfterWrite(5, TimeUnit.SECONDS)));
	}
```

```shell
Caused by: java.lang.ClassCastException: class org.apache.fury.serializer.ObjectSerializer cannot be cast to class org.apache.fury.serializer.collection.AbstractCollectionSerializer (org.apache.fury.serializer.ObjectSerializer and org.apache.fury.serializer.collection.AbstractCollectionSerializer are in unnamed module of loader 'app')
	at net.sf.jsqlparser.statement.insert.InsertFuryCodec_1_1175962212_1656594904.writeCollectionClassInfo3$(InsertFuryCodec_1_1175962212_1656594904.java:536) ~[?:?]
	at net.sf.jsqlparser.statement.insert.InsertFuryCodec_1_1175962212_1656594904.writeFields4$(InsertFuryCodec_1_1175962212_1656594904.java:591) ~[?:?]
	at net.sf.jsqlparser.statement.insert.InsertFuryCodec_1_1175962212_1656594904.write(InsertFuryCodec_1_1175962212_1656594904.java:1084) ~[?:?]
	at org.apache.fury.serializer.collection.AbstractCollectionSerializer.writeSameTypeElements(AbstractCollectionSerializer.java:403) ~[fury-core-0.5.1.jar:0.5.1]
	at org.apache.fury.serializer.collection.AbstractCollectionSerializer.generalJavaWrite(AbstractCollectionSerializer.java:384) ~[fury-core-0.5.1.jar:0.5.1]
	at org.apache.fury.serializer.collection.AbstractCollectionSerializer.writeElements(AbstractCollectionSerializer.java:313) ~[fury-core-0.5.1.jar:0.5.1]
	at org.apache.fury.serializer.collection.AbstractCollectionSerializer.write(AbstractCollectionSerializer.java:298) ~[fury-core-0.5.1.jar:0.5.1]
	at org.apache.fury.Fury.writeData(Fury.java:552) ~[fury-core-0.5.1.jar:0.5.1]
	at org.apache.fury.Fury.write(Fury.java:316) ~[fury-core-0.5.1.jar:0.5.1]
	at org.apache.fury.Fury.serialize(Fury.java:250) ~[fury-core-0.5.1.jar:0.5.1]
	at org.apache.fury.Fury.serialize(Fury.java:204) ~[fury-core-0.5.1.jar:0.5.1]
```

### What did you expect to see?

Normal serialization

### What did you see instead?

class org.apache.fury.serializer.ObjectSerializer cannot be cast to class org.apache.fury.serializer.collection.AbstractCollectionSerializer

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
I noticed you used Fury instead of TheadSafeFury as a global static serializer. This is not thread safe, maybe this is the reason why this error happen

**Comment by KouShenhai** [comment]
Thank you for your reply. I have changed the data type of Caffeine cache from storing objects to storing arrays. The code issue has been resolved. Thank you

> 我注意到您使用 Fury 而不是 TheadSafeFury 作为全局静态序列化程序。这不是线程安全的，也许这就是发生此错误的原因
