### ISSUE TITLE
NullPointer from ThreadPoolFury.serialize

### ISSUE THREAD

**Issue by davidnadeau** [apache/fury#1763]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

0.6.0

### Component(s)

Java

### Minimal reproduce step

I have not been able to produce a minimal code example. It is very difficult to debug, since I am just getting: `java.lang.NullPointerException: null` as the exception. This is occurring when trying to serialize values.

I am also seeing some errors when trying to deserialize values (far fewer then the serialize error):
```
java.lang.NullPointerException: Cannot invoke "String.length()" because "msg" is null
	at org.apache.fury.logging.FuryLogger.log(FuryLogger.java:145)
	at org.apache.fury.logging.FuryLogger.error(FuryLogger.java:133)
	at org.apache.fury.pool.FuryPooledObjectFactory.getPooledCache(FuryPooledObjectFactory.java:95)
	at org.apache.fury.pool.ThreadPoolFury.execute(ThreadPoolFury.java:77)
	at org.apache.fury.pool.ThreadPoolFury.deserialize(ThreadPoolFury.java:135)
```

### What did you expect to see?

No null pointers when serializing and deserializing data.

### What did you see instead?

j.l.NullPointerException: null

### Anything Else?

I am using Scala 2.13.12, my application runs in k8s (debian 11), with JDK 17. In production there are around 200 pods, and 20 cpus per pod.

I configure Fury in a scala Object like so:

```scala
object FuryUtils {
  lazy val fury = Fury
    .builder()
    .withLanguage(Language.JAVA)
    .withScalaOptimizationEnabled(true)
    .requireClassRegistration(false)
    .withRefTracking(false)
    .buildThreadSafeFuryPool(Runtime.getRuntime.availableProcessors() * 2, Runtime.getRuntime.availableProcessors() * 2)
}
```

and i serialize/deserialze my values like:
```scala
fury.serialize(value)
fury.deserialize(bytes).asInstanceOf[MyData]
```

I am calling this function ~20,000 times per second. And it is failing ~30 times per second.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by davidnadeau** [comment]
Maybe this is related? https://github.com/apache/fury/issues/1524

**Comment by chaokunyang** [comment]
> Maybe this is related? #1524

https://github.com/apache/fury/issues/1524 will happen only when you register classes in different threads at the same time.

**Comment by chaokunyang** [comment]
@davidnadeau Could you use the snapshot jar instead? It fixed NPE in FUryLogger, and will provide the stacktrace of the ro ot cause

**Comment by davidnadeau** [comment]
Oh nice, thank you. I'll try that.

**Comment by davidnadeau** [comment]
I got more details using the snapshot version:
```
j.l.NullPointerException: null
	at c.g.c.b.Preconditions.checkNotNull(Preconditions.java:906)
	at c.g.c.c.LocalCache.getIfPresent(LocalCache.java:4024)
	at c.g.c.c.LocalCache$LocalManualCache.getIfPresent(LocalCache.java:4927)
	at o.a.f.p.FuryPooledObjectFactory.getPooledCache(FuryPooledObjectFactory.java:88)
	... 45 common frames omitted
Wrapped by: j.l.RuntimeException: java.lang.NullPointerException
	at o.a.f.p.FuryPooledObjectFactory.getPooledCache(FuryPooledObjectFactory.java:96)
	at o.a.f.p.ThreadPoolFury.execute(ThreadPoolFury.java:77)
	... 44 common frames omitted
Wrapped by: j.l.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at o.a.f.p.ThreadPoolFury.execute(ThreadPoolFury.java:82)
	at o.a.f.p.ThreadPoolFury.deserialize(ThreadPoolFury.java:135)
	at c.e.m.c.s.m.FuryUtils$MemcachedSerializableRivuletListingFeatures$.deserialize(FuryUtils.scala:25)
	at c.e.m.c.s.m.FuryUtils$MemcachedSerializableRivuletListingFeatures$.deserialize(FuryUtils.scala:17)
	at c.e.m.c.s.m.MemcachedSerializable$.deserialize(MemcachedSerializable.scala:50)
	at c.e.m.c.s.m.MemcachedClient.$anonfun$get$5(MemcachedClient.scala:79)
	at scala.util.Try$.apply(Try.scala:210)
	at c.e.m.c.s.m.MemcachedClient.$anonfun$get$4(MemcachedClient.scala:79)
	at s.c.Iterator$$anon$10.nextCur(Iterator.scala:594)
	at s.c.Iterator$$anon$10.hasNext(Iterator.scala:608)
	at s.c.mutable.Growable.addAll(Growable.scala:61)
	at s.c.mutable.Growable.addAll$(Growable.scala:57)
	at s.c.i.MapBuilderImpl.addAll(Map.scala:710)
	at s.c.immutable.Map$.from(Map.scala:661)
	at s.c.immutable.Map$.from(Map.scala:172)
	at s.collection.MapOps.flatMap(Map.scala:321)
	at s.collection.MapOps.flatMap$(Map.scala:321)
	at s.c.AbstractMap.flatMap(Map.scala:405)
	at c.e.m.c.s.m.MemcachedClient.$anonfun$get$3(MemcachedClient.scala:78)
	at c.t.util.Return.map(Try.scala:308)
	at c.t.util.Future.$anonfun$map$1(Future.scala:1913)
	at c.t.u.Promise$TryTransformer.liftedTree2$1(Promise.scala:275)
	at c.t.u.Promise$TryTransformer.k(Promise.scala:275)
	at c...."
```

**Comment by LiangliangSui** [comment]
Hi @davidnadeau , from the backtrce, should be that `classLoaderLocal.get()` got the null `ClassLoader`

```java
// org.apache.fury.pool.FuryPooledObjectFactory
public ClassLoaderFuryPooled getPooledCache() {
  try {
    ClassLoader classLoader = classLoaderLocal.get();
    ClassLoaderFuryPooled classLoaderFuryPooled =
        classLoaderFuryPooledCache.getIfPresent(classLoader);
    if (classLoaderFuryPooled == null) {
      // double check cache
      return getOrAddCache(classLoader);
    }
    return classLoaderFuryPooled;
  } catch (Exception e) {
    LOG.error(e.getMessage(), e);
    throw new RuntimeException(e);
  }
}
```

The `ClassLoader` obtained from the `classLoaderLocal` initialization function is null
```java
// org.apache.fury.pool.FuryPooledObjectFactory
private final ThreadLocal<ClassLoader> classLoaderLocal =
      ThreadLocal.withInitial(() -> Thread.currentThread().getContextClassLoader());
```

`Thread#getContextClassLoader` seems to be a focus of analysis.
