### ISSUE TITLE
[Question] <title> Problem with Fury Serialization/Deserialization for Nested Classes

### ISSUE THREAD

**Issue by Moouna** [apache/fury#1893]
### Problem with Fury Serialization/Deserialization for Nested Classes

I’m using **Fury** for serializing and deserializing two different classes (`Source` and `Target`) that have similar structures but different inner classes (`SourceInner` and `TargetInner`). Serialization works when handling a list (`innerList`), but it fails when serializing a single field (`inner`), throwing a `ClassCastException`.

### Classes:
```java
@Data
public class Source {
    private SourceInner inner;
    private List<SourceInner> innerList;
}

public class SourceInner {
}

@Data
public class Target {
    private TargetInner inner;
    private List<TargetInner> innerList;
}

public class TargetInner {
}
```

### Test Case 1: Success

Serialization and deserialization works fine when using the `innerList` field (a list of `SourceInner`):
```java
@Test
public void testFurySuccess() {
    Source source = new Source();
    source.setInnerList(new ArrayList<>());
    source.getInnerList().add(new SourceInner());

    Fury fury = Fury.builder()
            .withLanguage(Language.JAVA)
            .requireClassRegistration(false)
            .withClassVersionCheck(false)
            .withCodegen(true)
            .withJdkClassSerializableCheck(false)
            .build();

    byte[] bytes = fury.serializeJavaObject(source);
    Target target = fury.deserializeJavaObject(bytes, Target.class);
    System.out.println(target);  // Success
}
```

### Test Case 2: Failure

However, when trying to serialize the `inner` field (a single instance of `SourceInner`), it fails with a `ClassCastException`:
```java
@Test
public void testFuryFailed() {
    Source source = new Source();
    source.setInner(new SourceInner());

    Fury fury = Fury.builder()
            .withLanguage(Language.JAVA)
            .requireClassRegistration(false)
            .withClassVersionCheck(false)
            .withCodegen(true)
            .withJdkClassSerializableCheck(false)
            .build();

    byte[] bytes = fury.serializeJavaObject(source);
    Target target = fury.deserializeJavaObject(bytes, Target.class);  // Fails
    System.out.println(target);
}
```

### Error:
```
java.lang.ClassCastException: SourceInner cannot be cast to TargetInner
    at org.apache.fury.format.dto.TargetFuryCodec_0.read(TargetFuryCodec_0.java:242)
    at org.apache.fury.Fury.readDataInternal(Fury.java:958)
    at org.apache.fury.Fury.deserializeJavaObject(Fury.java:1117)
    ...
```

### Question:
How can I make Fury correctly deserialize `SourceInner` to `TargetInner` without a `ClassCastException`? Is there a way to map `SourceInner` to `TargetInner` automatically, or do I need to implement custom logic?

Thanks in advance for any suggestions!

**Comment by chaokunyang** [comment]
You can create two Fury instance, one for serializaiton, another for deserializaiton, and register those classes to same class id. If the class has different schema, you also need to set CompatileMode to Compatible

**Comment by Moouna** [comment]
It works.

```java
Source source = new Source();
source.setInner(new SourceInner());

Fury furySerialize = Fury.builder()
        .withLanguage(Language.JAVA)
        .requireClassRegistration(false)
        .withClassVersionCheck(false)
        .withCodegen(true)
        .withCompatibleMode(CompatibleMode.COMPATIBLE)
        .withJdkClassSerializableCheck(false)
        .build();

Fury furyDeserialize = Fury.builder()
        .withLanguage(Language.JAVA)
        .requireClassRegistration(false)
        .withClassVersionCheck(false)
        .withCodegen(true)
        .withCompatibleMode(CompatibleMode.COMPATIBLE)
        .withJdkClassSerializableCheck(false)
        .build();

Short id = 3547;
Short innerId = 3548;
furySerialize.register(Source.class, id);
furySerialize.register(SourceInner.class, innerId);
furyDeserialize.register(Target.class, id);
furyDeserialize.register(TargetInner.class, innerId);
byte[] bytes = furySerialize.serializeJavaObject(source);
Target target = furyDeserialize.deserializeJavaObject(bytes, Target.class);
System.out.println(target);
```
Do you have a more effective solution?I mean, when there are too many classes, registering them one by one is not very friendly for the project.

**Comment by chaokunyang** [comment]
Sadly I don't have a better solution for such cases. Maybe you can write a loop to do such things
