### ISSUE TITLE
Class with missing field failed to deserialize on new version

### ISSUE THREAD

**Issue by orisgarno** [apache/fury#1972]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

java v0.9.0

### Component(s)

Java

### Minimal reproduce step

```
BaseFury s = FuryFury.builder()
.withLanguage(Language.JAVA)
.withRefTracking(true)
.withIntCompressed(true)
.withLongCompressed(true)
.withStringCompressed(true)
.withCompatibleMode(CompatibleMode.COMPATIBLE)
.requireClassRegistration(false)
.withAsyncCompilation(true)
.serializeEnumByName(true)
.buildThreadSafeFury()
```

```
public class PrivateFliedClassNumberOne {
  private boolean privateBoolean = true;
  private int privateInt = 10;
  private String privateString = "notNull";
  private Map<String, String> privateMap = Map.of("a", "b");
  private List<String> privateList = List.of("l");
  private PrivateFieldSubClass privateFieldSubClass = new PrivateFieldSubClass();
}
```
```
public class PrivateFliedClassNumberTwoWithMissingField {

  private Map<String, String> privateMap = Map.of("a", "b");
  private int privateInt = 10;
  private PrivateFieldSubClass privateFieldSubClass = new PrivateFieldSubClass();
  private List<String> privateList = List.of("l");
  private boolean privateBoolean = true;
}
```

code to repro
```
    PrivateFliedClassNumberOne privateField = new PrivateFliedClassNumberOne();
    byte[] serialized = s.serialize(privateField);


    PrivateFliedClassNumberTwoWithMissingField privateField2 = s.deserialize(serialized, PrivateFliedClassNumberTwoWithMissingField.class);
```

### What did you expect to see?

Should be able to deserialize successfully

### What did you see instead?

exception
```
Deserialize failed, read objects are: [PrivateFliedClassNumberTwoWithMissingField{privateMap={a=b}, privateInt=10, privateFieldSubClass=true, privateList=[l], privateBoolean=true}]

	at org.apache.fury.util.ExceptionUtils.handleReadFailed(ExceptionUtils.java:63)
	at org.apache.fury.Fury.deserializeJavaObject(Fury.java:1124)
	at org.apache.fury.Fury.deserializeJavaObject(Fury.java:1101)
	at org.apache.fury.ThreadLocalFury.deserializeJavaObject(ThreadLocalFury.java:202)
	at com.traveloka.demand.common.serde.fury.v0_9.FurySerde.deserialize(FurySerde.java:42)
	at serde.SerdeTestBase.testBasicPrivateField_diffClassScrambledField(SerdeTestBase.java:89)
	at serde.SerdeTestBase.runAll(SerdeTestBase.java:35)
	at com.traveloka.demand.common.FurySupplierTestV09.testFurySerde(FurySupplierTestV09.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 111 out of bounds for length 6
	at org.apache.fury.collection.ObjectArray.set(ObjectArray.java:58)
	at org.apache.fury.resolver.MapRefResolver.setReadObject(MapRefResolver.java:209)
	at org.apache.fury.Fury.readRef(Fury.java:875)
	at org.apache.fury.serializer.ObjectSerializer.readContainerFieldValue(ObjectSerializer.java:385)
	at org.apache.fury.serializer.ObjectSerializer.readAndSetFields(ObjectSerializer.java:318)
	at org.apache.fury.serializer.ObjectSerializer.read(ObjectSerializer.java:246)
	at org.apache.fury.Fury.readDataInternal(Fury.java:959)
	at org.apache.fury.Fury.deserializeJavaObject(Fury.java:1118)
	... 30 more

```

### Anything Else?

this is the first time i encounter this issue. 
i was using fury v0.5.1 and doesnt have this kind of problem. i am also tried to repro this on 0.5.1, but its not happening on that version.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
You need to use `serialize/deserialize` API instead. `serializeJavaObject deserializeJavaObject` will skip write class meta, so the dserialization side don't know how to handle schema inconsistency.

We should write class meta in `serializeJavaObject deserializeJavaObject` if `CompatibleMode` is used. Would you like to submit a PR?

**Comment by orisgarno** [comment]
Thank you to take a look at this issue @chaokunyang.
sure, will check what can i do.

**Comment by chaokunyang** [comment]
0.5.1 didn't enable meta share mode, so it go to another schema compatible protocol, which write type meta in a KV format. This format is not efficient, and has been replaced by scoped meta share mode in later versions. But we forget to write shared type meta for root class for `serializeJavaObject` API

**Comment by orisgarno** [comment]
after further read, seems serializeJavaObject API already write class def. which meta are you refering to? maybe if you can help to share some context or pointer it will be much help 
- https://github.com/apache/fury/blob/b43d521fa0eb29cc97fc60f4d7bfa4171c993c6a/java/fury-core/src/main/java/org/apache/fury/Fury.java#L1072
- https://github.com/apache/fury/blob/b43d521fa0eb29cc97fc60f4d7bfa4171c993c6a/java/fury-core/src/main/java/org/apache/fury/Fury.java#L1078

thank you

**Comment by orisgarno** [comment]
Hi @chaokunyang.
I've tried several approaches but am currently stuck.
I would greatly appreciate any pointers or suggestions you might have.
Thanks

**Comment by chaokunyang** [comment]
Hi @orisgarno which fury version  are you using when you try those approaches?

**Comment by orisgarno** [comment]
@chaokunyang the working one was v0.5.1, thee failing one is v0.9.0

**Comment by chaokunyang** [comment]
> after further read, seems serializeJavaObject API already write class def. which meta are you refering to? maybe if you can help to share some context or pointer it will be much help
> 
> * https://github.com/apache/fury/blob/b43d521fa0eb29cc97fc60f4d7bfa4171c993c6a/java/fury-core/src/main/java/org/apache/fury/Fury.java#L1072
> * https://github.com/apache/fury/blob/b43d521fa0eb29cc97fc60f4d7bfa4171c993c6a/java/fury-core/src/main/java/org/apache/fury/Fury.java#L1078
> 
> thank you

It didn't write class def, the correct code should looks like following:
```java
  public void serializeJavaObject(MemoryBuffer buffer, Object obj) {
    try {
      jitContext.lock();
      if (depth != 0) {
        throwDepthSerializationException();
      }
      if (config.isMetaShareEnabled()) {
        int startOffset = buffer.writerIndex();
        buffer.writeInt32(-1); // preserve 4-byte for meta start offsets.
        if (!refResolver.writeRefOrNull(buffer, obj)) {
          ClassInfo classInfo = classResolver.getOrUpdateClassInfo(obj.getClass());
          classResolver.writeClass(buffer, classInfo);
          writeData(buffer, classInfo, obj);
```
```java
  public <T> T deserializeJavaObject(MemoryBuffer buffer, Class<T> cls) {
    try {
      jitContext.lock();
      if (depth != 0) {
        throwDepthDeserializationException();
      }
      if (shareMeta) {
        readClassDefs(buffer);
      }
      T obj;
      int nextReadRefId = refResolver.tryPreserveRefId(buffer);
      if (nextReadRefId >= NOT_NULL_VALUE_FLAG) {
        ClassInfo classInfo;
        if (shareMeta) {
          classInfo = classResolver.readClassInfo(buffer);
        } else {
          classInfo = classResolver.getClassInfo(cls);
        }
        obj = (T) readDataInternal(buffer, classInfo);
        return obj;
      } else {
        return null;
      }
```

And when deserializing, you must register class by id to setup class mapping:
```java
  static BaseFury s = Fury.builder()
    .withRefTracking(true)
    .withCompatibleMode(CompatibleMode.COMPATIBLE)
    .requireClassRegistration(false)
    .serializeEnumByName(true)
    .buildThreadSafeFury();
  static BaseFury s1 = Fury.builder()
    .withRefTracking(true)
    .withCompatibleMode(CompatibleMode.COMPATIBLE)
    .requireClassRegistration(false)
    .serializeEnumByName(true)
    .buildThreadSafeFury();

  public static class PrivateFliedClassNumberOne {
    private boolean privateBoolean = true;
    private int privateInt = 10;
    private String privateString = "notNull";
    private Map<String, String> privateMap = ofHashMap("a", "b");
    private List<String> privateList = ofArrayList("l");
    private PrivateFieldSubClass privateFieldSubClass = new PrivateFieldSubClass();
  }

  public static class PrivateFliedClassNumberTwoWithMissingField {

    private Map<String, String> privateMap = ofHashMap("a", "b");
    private int privateInt = 10;
    private PrivateFieldSubClass privateFieldSubClass = new PrivateFieldSubClass();
    private List<String> privateList = ofArrayList("l");
    private boolean privateBoolean = true;
  }

  private static class PrivateFieldSubClass{}

  @Test
  public void test() {
    PrivateFliedClassNumberOne privateField = new PrivateFliedClassNumberOne();
    s.register(PrivateFliedClassNumberOne.class);
    byte[] serialized = s.serializeJavaObject(privateField);

    s1.register(PrivateFliedClassNumberTwoWithMissingField.class);
    PrivateFliedClassNumberTwoWithMissingField privateField2 = s1.deserializeJavaObject(
      serialized,
      PrivateFliedClassNumberTwoWithMissingField.class
    );
  }
```

**Comment by chaokunyang** [comment]
If you want to avoid class registeration, this will need more work, you need to extend `org.apache.fury.meta.ClassDef` and replace the original class with new passed class for all fields and the class. Then you need to extend `ClassResolver` with a new `readClassInfoWithMetaShare` method with passed deserialized type

**Comment by orisgarno** [comment]
Thanks for the code @chaokunyang .
After adding some extensive unit test(still on my local), it works. will make a pr for the changes and also the documentation.
Wondering though, do we need to register only the top most parent class?

not so sure for the solution to avoid class registration. seems quite some works. if it doesn't affect the performance, will try to take a look.

**Comment by chaokunyang** [comment]
If nested field classes are not registered, fury will skip those fields when there is a inconsistency. Currently fury will skip all incompatible fields if theiir declared types are not compatible. There is a PR #1870 which is working on this
