### ISSUE TITLE
bazel build failure: error loading package under directory '': error loading package 'cpp/fury'

### ISSUE THREAD

**Issue by chaokunyang** [apache/fury#1978]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

main

### Component(s)

C++

### Minimal reproduce step

bazel build //:cp_fury_so

### What did you expect to see?

build success

### What did you see instead?

```
ERROR: error loading package under directory '': error loading package 'cpp/fury': Unable to find package for @@[unknown repo 'rules_cc' requested from @@]//cc:defs.bzl: The repository '@@[unknown repo 'rules_cc' requested from @@]' could not be resolved: No repository visible as '@rules_cc' from main repository. Was the repository introduced in WORKSPACE? The WORKSPACE file is disabled by default in Bazel 8 (late 2024) and will be removed in Bazel 9 (late 2025), please migrate to Bzlmod. See https://bazel.build/external/migration.
2024-12-10 12:00:25,331 - ERROR - 
Traceback (most recent call last):
  File "/home/runner/work/fury/fury/./ci/run_ci.py", line 1[87](https://github.com/apache/fury/actions/runs/12247195666/job/34189138940#step:4:88), in <module>
    _parse_args()
  File "/home/runner/work/fury/fury/./ci/run_ci.py", line 183, in _parse_args
    args.func(**arg_dict)
  File "/home/runner/work/fury/fury/./ci/run_ci.py", line 84, in _run_cpp
    query_result = _exec_cmd("bazel query //...")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fury/fury/./ci/run_ci.py", line 43, in _exec_cmd
    result = subprocess.check_output(cmd, shell=True, universal_newlines=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel query //...' returned non-zero exit status 7.
Error: Process completed with exit code 1.
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
![image](https://github.com/user-attachments/assets/eb750806-1da6-4b5e-bc3a-20ab16f982a1)
