### ISSUE TITLE
fury.register error java.lang.NoSuchMethodException: no such constructor: java.util.concurrent.ConcurrentSkipListSet.<init>

### ISSUE THREAD

**Issue by lmm1990** [apache/fury#1986]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

Fury：0.9.0
os：windows10
graalvm：21.0.4

### Component(s)

Java

### Minimal reproduce step

[demo.zip](https://github.com/user-attachments/files/18211554/demo.zip)

see demo.zip

### What did you expect to see?

no error

### What did you see instead?

java.lang.UnsupportedOperationException: java.lang.NoSuchMethodException: no such constructor: java.util.concurrent.ConcurrentSkipListSet.<init>(Comparator)void/newInvokeSpecial
        at org.apache.fury.serializer.collection.CollectionSerializers$SortedSetSerializer.<init>(CollectionSerializers.java:209)
        at org.apache.fury.serializer.collection.CollectionSerializers$ConcurrentSkipListSetSerializer.<init>(CollectionSerializers.java:446)
        at org.apache.fury.serializer.collection.CollectionSerializers.registerDefaultSerializers(CollectionSerializers.java:836)
        at org.apache.fury.resolver.ClassResolver.addDefaultSerializers(ClassResolver.java:326)
        at org.apache.fury.resolver.ClassResolver.initialize(ClassResolver.java:313)
        at org.apache.fury.Fury.<init>(Fury.java:150)
        at org.apache.fury.config.FuryBuilder.newFury(FuryBuilder.java:419)
        at org.apache.fury.config.FuryBuilder.build(FuryBuilder.java:434)
        at com.example.demo.FuryUtils.lambda$static$0(FuryUtils.java:21)
        at org.apache.fury.util.LoaderBinding.setClassLoader(LoaderBinding.java:138)
        at org.apache.fury.util.LoaderBinding.setClassLoader(LoaderBinding.java:95)
        at org.apache.fury.ThreadLocalFury.lambda$new$2(ThreadLocalFury.java:67)
        at java.base@21.0.4/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357)
        at java.base@21.0.4/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
        at java.base@21.0.4/java.lang.ThreadLocal.get(ThreadLocal.java:194)
        at java.base@21.0.4/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at org.apache.fury.ThreadLocalFury.<init>(ThreadLocalFury.java:75)
        at com.example.demo.FuryUtils.<clinit>(FuryUtils.java:18)
        at com.example.demo.DemoApplication.main(DemoApplication.java:10)
        at java.base@21.0.4/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.NoSuchMethodException: no such constructor: java.util.concurrent.ConcurrentSkipListSet.<init>(Comparator)void/newInvokeSpecial
        at java.base@21.0.4/java.lang.invoke.MemberName.makeAccessException(MemberName.java:913)
        at java.base@21.0.4/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:994)
        at java.base@21.0.4/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3750)
        at java.base@21.0.4/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2837)
        at org.apache.fury.reflect.ReflectionUtils.lambda$getCtrHandle$1(ReflectionUtils.java:147)
        at java.base@21.0.4/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.apache.fury.reflect.ReflectionUtils.getCtrHandle(ReflectionUtils.java:143)
        at org.apache.fury.serializer.collection.CollectionSerializers$SortedSetSerializer.<init>(CollectionSerializers.java:207)
        ... 19 more
Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentSkipListSet.<init>(java.util.Comparator)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:335)
        at java.base@21.0.4/java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:213)
        at java.base@21.0.4/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
        at java.base@21.0.4/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:991)
        ... 25 more
2024-12-20 01:47:53 ERROR  FuryBuilder:422 [main] - Fury creation failed with classloader jdk.internal.loader.ClassLoaders$AppClassLoader@48140564
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.example.demo.DemoApplication.main(DemoApplication.java:10)
        at java.base@21.0.4/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.UnsupportedOperationException: java.lang.NoSuchMethodException: no such constructor: java.util.concurrent.ConcurrentSkipListSet.<init>(Comparator)void/newInvokeSpecial
        at org.apache.fury.serializer.collection.CollectionSerializers$SortedSetSerializer.<init>(CollectionSerializers.java:209)
        at org.apache.fury.serializer.collection.CollectionSerializers$ConcurrentSkipListSetSerializer.<init>(CollectionSerializers.java:446)
        at org.apache.fury.serializer.collection.CollectionSerializers.registerDefaultSerializers(CollectionSerializers.java:836)
        at org.apache.fury.resolver.ClassResolver.addDefaultSerializers(ClassResolver.java:326)
        at org.apache.fury.resolver.ClassResolver.initialize(ClassResolver.java:313)
        at org.apache.fury.Fury.<init>(Fury.java:150)
        at org.apache.fury.config.FuryBuilder.newFury(FuryBuilder.java:419)
        at org.apache.fury.config.FuryBuilder.build(FuryBuilder.java:434)
        at com.example.demo.FuryUtils.lambda$static$0(FuryUtils.java:21)
        at org.apache.fury.util.LoaderBinding.setClassLoader(LoaderBinding.java:138)
        at org.apache.fury.util.LoaderBinding.setClassLoader(LoaderBinding.java:95)
        at org.apache.fury.ThreadLocalFury.lambda$new$2(ThreadLocalFury.java:67)
        at java.base@21.0.4/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357)
        at java.base@21.0.4/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
        at java.base@21.0.4/java.lang.ThreadLocal.get(ThreadLocal.java:194)
        at java.base@21.0.4/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at org.apache.fury.ThreadLocalFury.<init>(ThreadLocalFury.java:75)
        at com.example.demo.FuryUtils.<clinit>(FuryUtils.java:18)
        ... 2 more
Caused by: java.lang.NoSuchMethodException: no such constructor: java.util.concurrent.ConcurrentSkipListSet.<init>(Comparator)void/newInvokeSpecial
        at java.base@21.0.4/java.lang.invoke.MemberName.makeAccessException(MemberName.java:913)
        at java.base@21.0.4/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:994)
        at java.base@21.0.4/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3750)
        at java.base@21.0.4/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2837)
        at org.apache.fury.reflect.ReflectionUtils.lambda$getCtrHandle$1(ReflectionUtils.java:147)
        at java.base@21.0.4/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.apache.fury.reflect.ReflectionUtils.getCtrHandle(ReflectionUtils.java:143)
        at org.apache.fury.serializer.collection.CollectionSerializers$SortedSetSerializer.<init>(CollectionSerializers.java:207)
        ... 19 more
Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentSkipListSet.<init>(java.util.Comparator)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:335)
        at java.base@21.0.4/java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:213)
        at java.base@21.0.4/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
        at java.base@21.0.4/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:991)
        ... 25 more

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Aliothmoon** [comment]
Is it running in AOT mode?

**Comment by Aliothmoon** [comment]
You may need to review this document [graalvm_guide](https://fury.apache.org/zh-CN/docs/guide/graalvm_guide#graalvm-native-image-%E4%BB%8B%E7%BB%8D)
You must create Fury as an static field of a class, and register all classes at the enclosing class initialize time.

**Comment by lmm1990** [comment]
Okay, I'll give it a try
